rvm:
  - jruby-18mode
  - jruby-19mode
branches:
  only:
    - master
gemfile:
  - Gemfile
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
