source 'http://rubygems.org'

rails_30 = ENV['RAILS_VERSION'] && ENV['RAILS_VERSION'] =~ /^3\.0\.\d+$/

gem 'rails', ENV['RAILS_VERSION'] || '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

#gem 'jruby-rack', '1.1.0.dev'

gem 'jruby-openssl'
gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
  gem 'therubyrhino'
end unless rails_30

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

